/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { ResponseNoContentResponse } from '../model/models';
import { UploadFileRequest } from '../model/models';


import { Configuration }                                     from '../configuration';



export interface FileControllerServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
     * @param uploadFileRequest 
     */
    uploadFile(uploadFileRequest?: UploadFileRequest, extraHttpRequestParams?: any): Observable<ResponseNoContentResponse>;

}
