/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreatePostRequest { 
    title?: string;
    content?: string;
    status?: string;
    tagIds?: Array<string>;
}

