/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ListPostRequest { 
    page?: number;
    size?: number;
    sort?: string;
    direction?: string;
    ignorePage?: boolean;
    searchTerm?: string;
    userId?: string;
    tagIds?: string[];
}

