/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDTO } from './user-dto';


export interface PageUserDTO { 
    items?: UserDTO[];
    totalElement?: number;
    totalPage?: number;
}

