/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostDTO } from './postDTO';


export interface PagePostDTO { 
    items?: Array<PostDTO>;
    totalElement?: number;
    totalPage?: number;
}

