/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PostDTO } from './post-dto';


export interface ResponsePostDTO { 
    success?: boolean;
    data?: PostDTO;
    message?: string;
    error?: Error;
}

