/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { IdDTO } from './id-dto';


export interface ResponseIdDTO { 
    success?: boolean;
    data?: IdDTO;
    message?: string;
    error?: Error;
}

