/**
 * OpenAPI definition
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PagePostDTO } from './page-post-dto';


export interface ResponsePagePostDTO { 
    success?: boolean;
    data?: PagePostDTO;
    message?: string;
    error?: Error;
}

