def branchName = ''
def unixTime = ''
def developmentTag = ''
pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        ENVIRONMENT        = 'dev'
    }
    stages {
        stage('Maven build') {
            steps {
                dir('blog-gateway'){
                     sh 'mvn -U clean install -Dmaven.test.skip=true -P server'
                }
            }
        }
        stage("Docker build") {
            steps {
                dir('blog-gateway'){
                    script {
                        branchName = env.ENVIRONMENT
                        unixTime = (new Date().time / 1000) as Integer
                        developmentTag = "${branchName}-${unixTime}"
                    }
                    sh "docker build -t anhdai0801/blog-gateway:${developmentTag} ."
                }
            }
        }
        stage("Docker push") {
            steps {
                sh "echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin"
                sh "docker push anhdai0801/blog-gateway:${developmentTag}"
                sh "docker rmi anhdai0801/blog-gateway:${developmentTag}"
            }
        }
    }
}