name: Check code BE
on:
  push:
    paths:
      - 'blog-common/**'
      - 'blog-proto/**'
      - 'blog-auth/**'
      - 'blog-account/**'
      - 'blog-file/**'
      - 'blog-post/**'
      - 'blog-gateway/**'
jobs:
  verify-code-be:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Create settings.xml'
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '[{"id": "github", "username": "${{ secrets.GITHUB_USERNAME }}", "password": "${{ secrets.GITHUB_PASSWORD }}"}]'
      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      - name: Verify quality common
        working-directory: blog-common
        run: mvn clean verify install --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Verify quality proto
        working-directory: blog-proto
        run: mvn clean verify install --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Verify quality account
        working-directory: blog-account
        run: mvn clean verify install --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Verify quality auth
        working-directory: blog-auth
        run: mvn clean verify install --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Verify quality file
        working-directory: blog-file
        run: mvn clean verify install --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Verify quality post
        working-directory: blog-post
        run: mvn clean verify install --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar
      - name: Verify quality gateway
        working-directory: blog-gateway
        run: mvn clean verify install --batch-mode org.sonarsource.scanner.maven:sonar-maven-plugin:sonar