name: Check code BE
on:
  push:
    paths:
      - 'blog-common/**'
      - 'blog-proto/**'
      - 'blog-auth/**'
      - 'blog-account/**'
      - 'blog-file/**'
      - 'blog-post/**'
      - 'blog-gateway/**'
jobs:
  verify-code-be:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: 'Create settings.xml'
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          servers: '[{"id": "github", "username": "${{ secrets.GITHUB_USERNAME }}", "password": "${{ secrets.GITHUB_PASSWORD }}"}]'
      - name: Verify
        run: |
          cd blog-common
          mvn clean install --batch-mode
          cd ../blog-proto
          mvn clean install --batch-mode
          cd ../blog-account
          mvn clean install --batch-mode
          cd ../blog-auth
          mvn clean install --batch-mode
          cd ../blog-file
          mvn clean install --batch-mode
          cd ../blog-post
          mvn clean install --batch-mode
          cd ../blog-gateway
          mvn clean install --batch-mode
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}