name: Publish blog package
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Publish package
        run: |
          cd blog-common
          mvn --batch-mode deploy
          cd ../blog-proto
          mvn --batch-mode deploy
          cd ../blog-account
          mvn --batch-mode deploy
          cd ../blog-file
          mvn --batch-mode deploy
          cd ../blog-post
          mvn --batch-mode deploy
          cd ../blog-gatewate
          mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}